### ISSUE TITLE
Siren access from HA

### ISSUE THREAD

**Issue by pophitru** [petrleocompel/hikaxpro_hacs#54] opened 2023-07-09 20:59 UTC
Hi!
Is there a way to trigger the wireless siren (DS-PS1-I-WE) from HA? I cannot see the siren in the list of AX PRO devices(

**Comment by petrleocompel** [comment] 2023-07-11 10:27
Duplicate of #44 
Sadly no API for triggering alarm :/ 
And since sirens are not giving lot of info there was no priority in showing them in devices.

Also I do not own any siren so testing this will be not easy. At least debug outputs from integration in debug mode will be required to help me integrate it.

Feel free to post it in #44

**Closed by petrleocompel** 2023-07-11 10:27 UTC
