### ISSUE TITLE
firmware 1.2.9 b230905 DS-PWA64-L-WE

### ISSUE THREAD

**Issue by trempetic92** [petrleocompel/hikaxpro_hacs#108] opened 2024-04-13 07:29 UTC
New firmware is giving bad request on arm/disarm.
Noticed they removed option for it on web interface. Most likely changed the parameter for area.

Anyone have any information? I am not directly using it for assistant, i am using it in my asp.net integration.

Cheers

**Comment by petrleocompel** [comment] 2024-04-13 07:36
I was having some concerns ... i will try to check it. But I am not going to upgrade firmware if it is true.

**Comment by trempetic92** [comment] 2024-04-13 09:02
For your information the new Hybrid PRO alarms are the same as the new AX PRO firmware, if it's solved, hybrid alarms would work as well. I will try to find correct params, since the node is still active, just params are bad.

**Comment by petrleocompel** [comment] 2024-04-15 10:18
Sadly HIkvision SDK is not updated. 
https://www.hikvision.com/us-en/support/download/sdk/
Still version V6.1.9.4_build20220412

Soo I cannot get the docs

**Comment by petrleocompel** [comment] 2024-04-15 10:22
Only never docs I could find is 2023
<img width="928" alt="image" src="https://github.com/petrleocompel/hikaxpro_hacs/assets/9423543/cc0a27a5-88c4-473e-85e4-5cab68b72cb3">

**Comment by trempetic92** [comment] 2024-04-15 13:50
Tested again, it still works, the bug occurs when you add installer and admin with same email address, and once the installer gave to user, he no longer have permissions to arm and disarm. Sorry, i have just seen the error msg after further debugging.

Tested now on newest firmware n240412 and it works.

**Comment by HappyPlotter** [comment] 2024-04-16 08:36
I can confirm that after changing the user to administrator the arm/disarm works

**Comment by petrleocompel** [comment] 2024-04-17 04:50
I will add info to `README.md` and issues will be closed. (#108 #107) 

Sadly for you guys. I installed system myself. So only person who has control over the system is me. 

Issues #106 and #97 will be asked to try again if changed because the code works... Only next problem on my mind is that during arming can be something triggering the PIR sensor and that is the next reason why you cannot arm the system.

Thank you for your cooperation and finding out. I would not find it because I am not going to give access to my system to anybody else.

**Comment by petrleocompel** [comment] 2024-04-17 05:32
Added section to `README.md` closing issue.

**Closed by petrleocompel** 2024-04-17 05:32 UTC

**Comment by HappyPlotter** [comment] 2024-04-22 11:20
I see in the documentation for the openAPI that there is X-UserLevel, I don't know if this is of any help
![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/111639418/55cdf5e3-1f30-401d-a6fb-e32b79b3fa36)

**Comment by petrleocompel** [comment] 2024-10-15 09:21
@HappyPlotter  -> Implemented - Released [v2.3.0](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.3.0) to prevent usage of installer account.
