### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by wifi75** [petrleocompel/hikaxpro_hacs#115] opened 2024-05-24 10:16 UTC
![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/31816231/cf0b616b-2429-48db-8421-59e9e985ca50)

[home-assistant_hikvision_axpro_2024-05-24T10-16-38.557Z.log](https://github.com/petrleocompel/hikaxpro_hacs/files/15431970/home-assistant_hikvision_axpro_2024-05-24T10-16-38.557Z.log)

**Comment by petrleocompel** [comment] 2024-05-24 21:38
duplicate of #114

**Closed by petrleocompel** 2024-05-24 21:38 UTC
