### ISSUE TITLE
Sensor for tilt detection

### ISSUE THREAD

**Issue by FPF92** [petrleocompel/hikaxpro_hacs#84] opened 2024-01-10 16:53 UTC
Hey guys,

I have a few magnet detectors with shock a tilt detection. I bought them to see the status of a window. Would be nice if this could be shown in HA too. 

Is it possible to implement that? 

Thanks for all kinds of help!

**Comment by petrleocompel** [comment] 2024-01-10 19:47
Please pair them, enable debug output and provide logs. To get info from devices. Also "model number" would be appreciated.

**Comment by FPF92** [comment] 2024-01-10 22:01
Thanks for your quick reply Petr!
It's the DS-PDMCK-EG2-WE.

And for debugging I guess I have tho enter the shell of Hikvision, right? Is there a manual for the procedure?

**Comment by petrleocompel** [comment] 2024-01-10 22:06
NO. In Homeassistant in integration configuration

**Comment by FPF92** [comment] 2024-01-12 08:50
```
2024-01-12 09:44:54.554 DEBUG (SyncWorker_0) [custom_components.hikvision] Axpro status: disarmed
2024-01-12 09:44:54.574 DEBUG (SyncWorker_0) [custom_components.hikvision] Zones: {'ZoneList': [{'Zone': {'id': 0, 'name': 'Drahtlose Zone 1', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 120, 'signalType': 'R3', 'temperature': 18, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'magneticContact', 'model': '0x00006', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'id': 1, 'enabled': False, 'mode': 'normalClose'}, {'id': 2, 'enabled': False, 'mode': 'normalClose'}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 1, 'abnormalOrNot': False}}, {'Zone': {'id': 1, 'name': 'Drahtlose Zone 2', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'signal': 121, 'realSignal': 156, 'signalType': 'R3', 'temperature': 15, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'slimMagneticContact', 'model': '0x00005', 'stayAway': False, 'zoneType': 'Instant', 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'version': 'V1.2.0', 'deviceNo': 2, 'abnormalOrNot': False}}, {'Zone': {'id': 2, 'name': 'Drahtlose Zone 3', 'status': 'online', 'sensorStatus': 'normal', 'MagnetShockCurrentStatus': {'magnetOpenStatus': False, 'magnetShockStatus': False, **'magnetTiltStatus': False**}, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 120, 'signalType': 'R3', 'temperature': 20, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'magnetShockDetector', 'model': '0x00017', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'enabled': False, 'id': 1, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}, {'enabled': False, 'id': 2, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 3, 'abnormalOrNot': False}}, {'Zone': {'id': 3, 'name': 'Drahtlose Zone 4', 'status': 'trigger', 'sensorStatus': 'normal', 'MagnetShockCurrentStatus': {'magnetOpenStatus': False, 'magnetShockStatus': False, **'magnetTiltStatus': True**}, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 128, 'signalType': 'R3', 'temperature': 25, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'magnetShockDetector', 'model': '0x00017', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'enabled': False, 'id': 1, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}, {'enabled': False, 'id': 2, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 5, 'abnormalOrNot': False}}]}
2024-01-12 09:44:54.594 DEBUG (SyncWorker_0) [custom_components.hikvision] { "ExDevStatus": { "OutputModList": [ ], "OutputList": [ ], "SirenList": [ { "Siren": { "id": 1, "name": "Sirene 1", "seq": "Q27076328", "status": "off", "tamperEvident": false, "charge": "normal", "chargeValue": 100, "signal": 121, "realSignal": 104, "signalType": "R3", "model": "0x7A001", "temperature": 23, "subSystemList": [ 1 ], "sirenColor": "white", "isViaRepeater": false, "version": "V1.1.256", "deviceNo": 4, "abnormalOrNot": false } } ], "RepeaterList": [ ], "CardReaderList": [ ], "KeypadList": [ ], "RemoteList": [ ], "TransmitterList": [ ] } }
2024-01-12 09:44:54.595 DEBUG (SyncWorker_0) [custom_components.hikvision] Relay status: {}
2024-01-12 09:44:54.596 DEBUG (MainThread) [custom_components.hikvision] Finished fetching hikvision data in 0.060 seconds (success: True)
```

**Comment by petrleocompel** [comment] 2024-01-12 08:53
Great. I see the sensor and "requested values". If today will be enough time I will implment and release new beta.

**Comment by petrleocompel** [comment] 2024-01-17 09:44
relased in [v2.1.0-beta14](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.1.0-beta14)

**Comment by FPF92** [comment] 2024-01-17 12:02
Just giving you a brief feedback. I installed beta15.

Magnet shock detection and Magnet tilt have the same issue:

They only receive the states:

- became unavailable
- became unknown

If I can support. Let me know.

**Comment by petrleocompel** [comment] 2024-01-17 12:03
Please get logs again.

**Comment by petrleocompel** [comment] 2024-01-18 21:14
@FPF92 Any possibility to get logs?

**Comment by FPF92** [comment] 2024-01-18 21:58
2024-01-18 22:52:58.475 DEBUG (SyncWorker_3) [custom_components.hikvision_axpro] Axpro status: disarmed
2024-01-18 22:52:58.487 DEBUG (SyncWorker_3) [custom_components.hikvision_axpro] Zones: {'ZoneList': [{'Zone': {'id': 0, 'name': 'Drahtlose Zone 1', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 110, 'signalType': 'R3', 'temperature': 18, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'magneticContact', 'model': '0x00006', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'id': 1, 'enabled': False, 'mode': 'normalClose'}, {'id': 2, 'enabled': False, 'mode': 'normalClose'}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 1, 'abnormalOrNot': False}}, {'Zone': {'id': 1, 'name': 'Drahtlose Zone 2', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'signal': 121, 'realSignal': 151, 'signalType': 'R3', 'temperature': 17, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'slimMagneticContact', 'model': '0x00005', 'stayAway': False, 'zoneType': 'Instant', 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'version': 'V1.2.0', 'deviceNo': 2, 'abnormalOrNot': False}}, {'Zone': {'id': 2, 'name': 'Drahtlose Zone 3', 'status': 'online', 'sensorStatus': 'normal', 'MagnetShockCurrentStatus': {'magnetOpenStatus': False, 'magnetShockStatus': False, 'magnetTiltStatus': False}, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 118, 'signalType': 'R3', 'temperature': 20, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'magnetShockDetector', 'model': '0x00017', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'enabled': False, 'id': 1, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}, {'enabled': False, 'id': 2, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 3, 'abnormalOrNot': False}}, {'Zone': {'id': 3, 'name': 'Drahtlose Zone 4', 'status': 'online', 'sensorStatus': 'normal', 'MagnetShockCurrentStatus': {'magnetOpenStatus': False, 'magnetShockStatus': False, 'magnetTiltStatus': False}, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 121, 'signalType': 'R3', 'temperature': 24, 'subSystemNo': 2, 'linkageSubSystem': [2], 'detectorType': 'magnetShockDetector', 'model': '0x00017', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'enabled': False, 'id': 1, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}, {'enabled': False, 'id': 2, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 5, 'abnormalOrNot': False}}]}
2024-01-18 22:52:58.506 DEBUG (SyncWorker_3) [custom_components.hikvision_axpro] { "ExDevStatus": { "OutputModList": [ ], "OutputList": [ ], "SirenList": [ { "Siren": { "id": 1, "name": "Sirene 1", "seq": "Q27076328", "status": "off", "tamperEvident": false, "charge": "normal", "chargeValue": 100, "signal": 121, "realSignal": 137, "signalType": "R3", "model": "0x7A001", "temperature": 22, "subSystemList": [ 2 ], "sirenColor": "white", "isViaRepeater": false, "version": "V1.1.256", "deviceNo": 4, "abnormalOrNot": false } } ], "RepeaterList": [ ], "CardReaderList": [ ], "KeypadList": [ ], "RemoteList": [ ], "TransmitterList": [ ] } }

I don't get info from that

**Comment by petrleocompel** [comment] 2024-01-18 22:00
I will see what I can do.

**Comment by FPF92** [comment] 2024-01-18 22:08
Thanks!

With a second sensor I have a better log:

2024-01-18 23:05:28.489 DEBUG (SyncWorker_8) [custom_components.hikvision_axpro] Zones: {'ZoneList': [{'Zone': {'id': 0, 'name': 'Drahtlose Zone 1', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 110, 'signalType': 'R3', 'temperature': 19, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'magneticContact', 'model': '0x00006', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'id': 1, 'enabled': False, 'mode': 'normalClose'}, {'id': 2, 'enabled': False, 'mode': 'normalClose'}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 1, 'abnormalOrNot': False}}, {'Zone': {'id': 1, 'name': 'Drahtlose Zone 2', 'status': 'online', 'sensorStatus': 'normal', 'magnetOpenStatus': False, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'signal': 121, 'realSignal': 151, 'signalType': 'R3', 'temperature': 18, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'slimMagneticContact', 'model': '0x00005', 'stayAway': False, 'zoneType': 'Instant', 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'version': 'V1.2.0', 'deviceNo': 2, 'abnormalOrNot': False}}, {'Zone': {'id': 2, 'name': 'Drahtlose Zone 3', 'status': 'online', 'sensorStatus': 'normal', 'MagnetShockCurrentStatus': {'magnetOpenStatus': False, 'magnetShockStatus': False, 'magnetTiltStatus': False}, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 121, 'signalType': 'R3', 'temperature': 21, 'subSystemNo': 1, 'linkageSubSystem': [1], 'detectorType': 'magnetShockDetector', 'model': '0x00017', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'enabled': False, 'id': 1, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}, {'enabled': False, 'id': 2, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 3, 'abnormalOrNot': False}}, {'Zone': {'id': 3, 'name': 'Drahtlose Zone 4', 'status': 'trigger', 'sensorStatus': 'normal', 'MagnetShockCurrentStatus': {'magnetOpenStatus': False, 'magnetShockStatus': False, 'magnetTiltStatus': True}, 'tamperEvident': False, 'shielded': False, 'bypassed': False, 'armed': False, 'isArming': False, 'alarm': False, 'charge': 'normal', 'chargeValue': 100, 'signal': 121, 'realSignal': 121, 'signalType': 'R3', 'temperature': 25, 'subSystemNo': 2, 'linkageSubSystem': [2], 'detectorType': 'magnetShockDetector', 'model': '0x00017', 'stayAway': False, 'zoneType': 'Instant', 'InputList': [{'enabled': False, 'id': 1, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}, {'enabled': False, 'id': 2, 'mode': 'normalClose', 'pulseNum': 8, 'timeout': 20}], 'isViaRepeater': False, 'zoneAttrib': 'wireless', 'isSupportAddType': True, 'version': 'V1.2.0', 'deviceNo': 5, 'abnormalOrNot': False}}]}
2024-01-18 23:05:28.507 DEBUG (SyncWorker_8) [custom_components.hikvision_axpro] { "ExDevStatus": { "OutputModList": [ ], "OutputList": [ ], "SirenList": [ { "Siren": { "id": 1, "name": "Sirene 1", "seq": "Q27076328", "status": "off", "tamperEvident": false, "charge": "normal", "chargeValue": 100, "signal": 121, "realSignal": 136, "signalType": "R3", "model": "0x7A001", "temperature": 22, "subSystemList": [ 2 ], "sirenColor": "white", "isViaRepeater": false, "version": "V1.1.256", "deviceNo": 4, "abnormalOrNot": false } } ], "RepeaterList": [ ], "CardReaderList": [ ], "KeypadList": [ ], "RemoteList": [ ], "TransmitterList": [ ] } }

But also with this sensor you dont see changes of the HA sensors

**Comment by Drealine** [comment] 2024-01-19 18:31
Hi. Same issue for me. I've some multiple tilt and choc detector. Only unavailable state is show in HA history.

**Comment by petrleocompel** [comment] 2024-01-19 18:34
The issue is confirmed that exist. Currently it is just harder for me to fix it... Because I do not have shock and tilt sensors.
If you have better info it is appreciated to comment.

**Comment by Drealine** [comment] 2024-01-21 15:35
Hi @petrleocompel 
By now, I can't have some logs in HA. Try to enable debug in integration but nothing. Maybe missing thing ?

**Comment by petrleocompel** [comment] 2024-01-21 15:39
In configuration of integration there is "debug output"

**Comment by Drealine** [comment] 2024-01-21 15:40
Yes true. But nothing happen

**Comment by Drealine** [comment] 2024-01-21 15:41
No event when open a door. Maybe the alarm should be in armed state ?

**Comment by petrleocompel** [comment] 2024-01-21 15:41
Also it will give out output in "interval of 30 sec" (default)

**Comment by Drealine** [comment] 2024-01-21 15:46
That's really stange. Nothing happen. 
When open a door, just status in the device change to triggered. 
See option in integration : 
![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/61891683/e6972fb0-4ab1-4230-9a85-b15e68c143fd)


And interval is set to 2sec for me.

**Comment by petrleocompel** [comment] 2024-01-21 15:47
You have to restart HA after enabling this option

**Comment by Drealine** [comment] 2024-01-21 15:50
Always nothing. No log in HomeAssistant Core page.

**Comment by petrleocompel** [comment] 2024-01-21 15:53
Sadly I cannot test with HA Core. I use it in container to have more control over my instance. 
It is not needed. Creator of issue provided logs. It just takes time. You have to wait.

**Comment by Drealine** [comment] 2024-01-21 16:02
Yes thank you. I would like to give more logs. It's that strange that HA not retrieve info logs.

**Comment by Drealine** [comment] 2024-01-21 16:04
Ok founded. I've to enable debug mode too here : 
![image](https://github.com/petrleocompel/hikaxpro_hacs/assets/61891683/ff72a9a7-cfeb-4503-a8f1-d74049f95950)

**Comment by Drealine** [comment] 2024-01-21 16:13
Ok so I've more logs : 
1st : Integration log some unkown entity : 

`2024-01-21 17:06:53.689 DEBUG (MainThread) [custom_components.hikvision_axpro.sensor] setting up - sensors: [<entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>, <entity unknown.unknown=unknown>]`


2nd : This is the json output of my detector : 

`'Zone':{
'id':9,
'name':'##HIDESENSORNAME##',
'status':'online',
'sensorStatus':'normal',
'MagnetShockCurrentStatus':{
'magnetOpenStatus':False,
'magnetShockStatus':False,
'magnetTiltStatus':False
},
'tamperEvident':False,
'shielded':False,
'bypassed':False,
'armed':False,
'isArming':False,
'alarm':False,
'charge':'normal',
'chargeValue':100,
'signal':121,
'realSignal':128,
'signalType':'R3',
'temperature':22,
'subSystemNo':1,
'linkageSubSystem':[
1
],
'detectorType':'magnetShockDetector',
'model':'0x00017',
'stayAway':False,
'zoneType':'Instant',
'InputList':[
{
'enabled':False,
'id':1,
'mode':'normalClose',
'pulseNum':8,
'timeout':20
},
{
'enabled':False,
'id':2,
'mode':'normalClose',
'pulseNum':8,
'timeout':20
}
],
'isViaRepeater':False,
'zoneAttrib':'wireless',
'isSupportAddType':True,
'version':'V1.4.0',
'deviceNo':11,
'abnormalOrNot':False`

**Comment by petrleocompel** [comment] 2024-01-22 09:19
Found it. Closing with release [v2.1.0-beta16](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.1.0-beta16)

**Closed by petrleocompel** 2024-01-22 09:19 UTC
Labels: enhancement

**Comment by Drealine** [comment] 2024-01-22 12:53
Confirm it work. Thanks a lot!
