### ISSUE TITLE
status updates not detected

### ISSUE THREAD

**Issue by leciuk81** [petrleocompel/hikaxpro_hacs#45] opened 2023-05-22 09:52 UTC
Good morning @petrleocompel there is a new problem.
The magnetic contacts are not updated, the state seems frozen even if opening and closing the window this does not change anymore.
I installed v2.0.0-beta10 but the problem persists.
In Hikvision app it works fine. I am attaching the 2 pictures

![Screenshot_20230522_114028_Home Assistant](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/8bc0330e-fce5-42d5-9cf8-b528e3794427)

![Screenshot_20230522_114104_Hik-Connect](https://github.com/petrleocompel/hikaxpro_hacs/assets/126766794/cbb0342f-57f1-45b0-b201-8bd5d4b80b0f)

Furthermore, as you can see from the photo, the magnet icon is not recognized for DS-PDMCK-EG2_WE(B) devices.

I am also attaching the debug
[home-assistant_hikvision_axpro_2023-05-22T09-49-23.612Z.log](https://github.com/petrleocompel/hikaxpro_hacs/files/11529632/home-assistant_hikvision_axpro_2023-05-22T09-49-23.612Z.log)

**Comment by petrleocompel** [comment] 2023-05-30 12:50
In the log there is not a reinit call. Please do following steps:
- enable debug in integration via configuration
- reload integration
- open your window (magnet trigger)
- wait 30 sec
- close window (magnet trigger)
- download the log

it will give me an load devices call. And more info about your system to get more details.

Currently I see there is no trigger during the logging you provided. As you can see "magnetStatus" is always same.

**Comment by petrleocompel** [comment] 2023-06-08 12:24
Good thing to mention! 
Are you in what time interval are you testing this ? 

Default pull interval is 30 seconds.

**Comment by petrleocompel** [comment] 2023-07-11 12:22
Duplicate of #50
Please take a look on https://github.com/petrleocompel/hikaxpro_hacs/issues/50#issuecomment-1630725057

**Closed by petrleocompel** 2023-07-11 12:22 UTC
Labels: question
